param(
    [string]$OutputDir = "demo-output"
)

$ErrorActionPreference = "Stop"

$root = (Resolve-Path -LiteralPath (Join-Path $PSScriptRoot "..")).Path
$out = Join-Path $root $OutputDir
$case = Join-Path $out "demo.kdft.sqlite"
$report = Join-Path $out "report.html"

New-Item -ItemType Directory -Force -Path $out | Out-Null

foreach ($file in @($case, $report)) {
    if (Test-Path -LiteralPath $file) {
        Remove-Item -LiteralPath $file -Force
    }
}

$env:CARGO_TARGET_DIR = Join-Path $env:TEMP "kdft-v1-cargo-check-target"

cargo run -p kdft-cli -- case create --case $case --name "KDFT Demo Case" --examiner "Cristina" --json
cargo run -p kdft-cli -- bookmark folder-create --case $case --name "Findings" --comment "Demo report-ready findings" --json
cargo run -p kdft-cli -- bookmark create --case $case --folder-id 1 --type highlighted_data --data-type Text --title "First report finding" --comment "Generated by scripts/demo-report.ps1" --json
cargo run -p kdft-cli -- bookmark item-add --case $case --bookmark-id 1 --display-name "Selected bytes" --logical-path "/demo/file.txt" --selection-offset 128 --selection-length 16 --data-preview "keyword hit preview" --json
cargo run -p kdft-cli -- report export --case $case --output $report --json

Write-Output "CASE_PATH=$case"
Write-Output "REPORT_PATH=$report"
